/**
 * ============================================================
 * FALLBACK MOCK DATA
 * ============================================================
 * This data is used as a fallback until the database has real data.
 * Components should prefer fetching from the API (e.g. /api/tools)
 * and only fall back to these exports when the API is unavailable.
 *
 * TODO: Remove this file once real data is consistently available
 *       from the database and all components have been migrated.
 * ============================================================
 */

import type { Tool } from '@/types';

/** Fallback official tools — prefer fetching from /api/tools?isOfficial=true */
export const officialTools: Tool[] = [
  {
    id: 'presence-vision',
    name: 'PresenceVision',
    slug: 'presence-vision',
    description: 'AI-powered presence management and analytics',
    icon: '👁️',
    category: 'ai',
    pricing: { type: 'freemium' },
    rating: 4.8,
    reviewCount: 342,
    userCount: 12500,
    isOfficial: true,
    isFeatured: true,
    isTrending: true,
    creatorId: 'toolverse',
    creatorName: 'Toolverse',
    tags: ['AI', 'Analytics', 'Presence'],
    screenshots: [],
    createdAt: '2026-01-15',
    updatedAt: '2026-03-01',
  },
  {
    id: 'senrigan',
    name: 'SENRIGAN',
    slug: 'senrigan',
    description: 'AI-powered foresight analytics platform',
    icon: '🔮',
    category: 'ai',
    pricing: { type: 'subscription', price: 2980, currency: 'JPY', period: 'monthly' },
    rating: 4.9,
    reviewCount: 218,
    userCount: 8700,
    isOfficial: true,
    isFeatured: true,
    isTrending: true,
    creatorId: 'toolverse',
    creatorName: 'Toolverse',
    tags: ['AI', 'Foresight', 'Analytics'],
    screenshots: [],
    createdAt: '2026-01-20',
    updatedAt: '2026-03-05',
  },
  {
    id: 'patent-vision',
    name: 'PatentVision',
    slug: 'patent-vision',
    description: 'Patent search, analysis, and management',
    icon: '📜',
    category: 'analytics',
    pricing: { type: 'freemium' },
    rating: 4.7,
    reviewCount: 156,
    userCount: 5200,
    isOfficial: true,
    isFeatured: true,
    isTrending: false,
    creatorId: 'toolverse',
    creatorName: 'Toolverse',
    tags: ['Patent', 'Analysis', 'IP'],
    screenshots: [],
    createdAt: '2026-02-01',
    updatedAt: '2026-03-08',
  },
  {
    id: 'debt-navigator',
    name: 'Debt Navigator',
    slug: 'debt-navigator',
    description: 'Debt management and optimization navigator',
    icon: '🧭',
    category: 'finance',
    pricing: { type: 'free' },
    rating: 4.6,
    reviewCount: 89,
    userCount: 3400,
    isOfficial: true,
    isFeatured: false,
    isTrending: true,
    creatorId: 'toolverse',
    creatorName: 'Toolverse',
    tags: ['Finance', 'Debt', 'Management'],
    screenshots: [],
    createdAt: '2026-02-10',
    updatedAt: '2026-03-10',
  },
];

/** Fallback community tools — prefer fetching from /api/tools?isOfficial=false */
export const communityTools: Tool[] = [
  {
    id: 'ai-writer-pro',
    name: 'AI Writer Pro',
    slug: 'ai-writer-pro',
    description: 'Advanced AI writing assistant for professionals',
    icon: '✍️',
    category: 'ai',
    pricing: { type: 'subscription', price: 1980, currency: 'JPY', period: 'monthly' },
    rating: 4.5,
    reviewCount: 567,
    userCount: 23000,
    isOfficial: false,
    isFeatured: true,
    isTrending: true,
    creatorId: 'creator-1',
    creatorName: 'AI Labs',
    tags: ['AI', 'Writing', 'Content'],
    screenshots: [],
    createdAt: '2026-02-15',
    updatedAt: '2026-03-11',
  },
  {
    id: 'task-flow',
    name: 'TaskFlow',
    slug: 'task-flow',
    description: 'Intelligent task management with AI prioritization',
    icon: '📋',
    category: 'productivity',
    pricing: { type: 'freemium' },
    rating: 4.4,
    reviewCount: 445,
    userCount: 18000,
    isOfficial: false,
    isFeatured: true,
    isTrending: true,
    creatorId: 'creator-2',
    creatorName: 'ProductivityCo',
    tags: ['Tasks', 'Productivity', 'AI'],
    screenshots: [],
    createdAt: '2026-01-10',
    updatedAt: '2026-03-09',
  },
  {
    id: 'code-pilot',
    name: 'CodePilot',
    slug: 'code-pilot',
    description: 'AI pair programming and code review assistant',
    icon: '💻',
    category: 'development',
    pricing: { type: 'subscription', price: 2480, currency: 'JPY', period: 'monthly' },
    rating: 4.7,
    reviewCount: 312,
    userCount: 15000,
    isOfficial: false,
    isFeatured: true,
    isTrending: true,
    creatorId: 'creator-3',
    creatorName: 'DevTools Inc',
    tags: ['Code', 'AI', 'Development'],
    screenshots: [],
    createdAt: '2026-02-05',
    updatedAt: '2026-03-10',
  },
  {
    id: 'market-sense',
    name: 'MarketSense',
    slug: 'market-sense',
    description: 'Real-time marketing analytics and insights',
    icon: '📊',
    category: 'marketing',
    pricing: { type: 'subscription', price: 3980, currency: 'JPY', period: 'monthly' },
    rating: 4.3,
    reviewCount: 198,
    userCount: 7600,
    isOfficial: false,
    isFeatured: false,
    isTrending: true,
    creatorId: 'creator-4',
    creatorName: 'MarketLab',
    tags: ['Marketing', 'Analytics', 'Insights'],
    screenshots: [],
    createdAt: '2026-01-25',
    updatedAt: '2026-03-07',
  },
  {
    id: 'auto-flow',
    name: 'AutoFlow',
    slug: 'auto-flow',
    description: 'No-code workflow automation builder',
    icon: '⚡',
    category: 'automation',
    pricing: { type: 'freemium' },
    rating: 4.6,
    reviewCount: 278,
    userCount: 11000,
    isOfficial: false,
    isFeatured: true,
    isTrending: false,
    creatorId: 'creator-5',
    creatorName: 'FlowLabs',
    tags: ['Automation', 'No-Code', 'Workflow'],
    screenshots: [],
    createdAt: '2026-02-20',
    updatedAt: '2026-03-11',
  },
  {
    id: 'fintrack',
    name: 'FinTrack',
    slug: 'fintrack',
    description: 'Personal finance tracking and budgeting',
    icon: '💰',
    category: 'finance',
    pricing: { type: 'free' },
    rating: 4.2,
    reviewCount: 456,
    userCount: 28000,
    isOfficial: false,
    isFeatured: false,
    isTrending: true,
    creatorId: 'creator-6',
    creatorName: 'FinanceLab',
    tags: ['Finance', 'Budget', 'Tracking'],
    screenshots: [],
    createdAt: '2026-01-05',
    updatedAt: '2026-03-06',
  },
  {
    id: 'design-studio',
    name: 'DesignStudio',
    slug: 'design-studio',
    description: 'AI-powered design tool for creators',
    icon: '🎨',
    category: 'creator',
    pricing: { type: 'subscription', price: 1480, currency: 'JPY', period: 'monthly' },
    rating: 4.5,
    reviewCount: 234,
    userCount: 9800,
    isOfficial: false,
    isFeatured: true,
    isTrending: false,
    creatorId: 'creator-7',
    creatorName: 'DesignCo',
    tags: ['Design', 'AI', 'Creative'],
    screenshots: [],
    createdAt: '2026-02-08',
    updatedAt: '2026-03-09',
  },
  {
    id: 'data-lens',
    name: 'DataLens',
    slug: 'data-lens',
    description: 'Advanced data visualization and analytics',
    icon: '🔬',
    category: 'analytics',
    pricing: { type: 'freemium' },
    rating: 4.4,
    reviewCount: 167,
    userCount: 6500,
    isOfficial: false,
    isFeatured: false,
    isTrending: false,
    creatorId: 'creator-8',
    creatorName: 'DataLabs',
    tags: ['Data', 'Visualization', 'Analytics'],
    screenshots: [],
    createdAt: '2026-01-30',
    updatedAt: '2026-03-04',
  },
];

/** Fallback combined tools list — prefer fetching from /api/tools */
export const allTools = [...officialTools, ...communityTools];

/** Fallback categories — prefer fetching from /api/categories */
export const categories = [
  { id: 'ai', icon: '🧠', color: 'from-violet-500 to-purple-600' },
  { id: 'productivity', icon: '⚡', color: 'from-blue-500 to-cyan-500' },
  { id: 'finance', icon: '📈', color: 'from-emerald-500 to-green-600' },
  { id: 'marketing', icon: '🎯', color: 'from-orange-500 to-red-500' },
  { id: 'development', icon: '⌨️', color: 'from-slate-500 to-slate-700' },
  { id: 'creator', icon: '🎬', color: 'from-pink-500 to-rose-600' },
  { id: 'automation', icon: '⚙️', color: 'from-amber-500 to-yellow-600' },
  { id: 'analytics', icon: '📊', color: 'from-indigo-500 to-blue-600' },
  { id: 'security', icon: '🛡️', color: 'from-red-500 to-rose-700' },
  { id: 'healthcare', icon: '🏥', color: 'from-teal-500 to-cyan-600' },
  { id: 'education', icon: '🎓', color: 'from-sky-500 to-blue-600' },
  { id: 'ecommerce', icon: '🛒', color: 'from-fuchsia-500 to-pink-600' },
  { id: 'communication', icon: '💬', color: 'from-green-500 to-emerald-600' },
  { id: 'iot', icon: '📡', color: 'from-cyan-500 to-teal-600' },
  { id: 'media', icon: '🎥', color: 'from-rose-500 to-orange-500' },
  { id: 'logistics', icon: '🚀', color: 'from-purple-500 to-indigo-600' },
] as const;
